/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Lista.Nodo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author lazarod
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    File file;
    Nodo ptr;
    String[][] primas = new String[27][2];
    ;
    ArrayList<Character> probadas = new ArrayList();
    int indice = 0;
    int indice2 = 0;
    int indice3 = 0;

    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        file_path = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(file_path, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(file_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(555, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String tienerecursividad(String p) {
        String cab = p.substring(0, 1);
        String[] prods = p.split("\\|");
        int i = 0;
        String r = "";
        while (prods.length > i) {
            if (i == 0) {
                if (prods[i].substring(3, 4).equals(cab)) {
                    r = i + "_";
                }
                i++;
            } else {
                if (prods[i].substring(0, 1).equals(cab)) {
                    r = r + i + "_";
                }
                i++;
            }
        }
        if (!"".equals(r)) {
            return r;
        } else {
            return "-1";
        }
    }

    public void agregar_prod(String p) {
        String nt = p.substring(0, 1);
        if (ptr == null) {
            Nodo c = new Nodo(p);
            ptr = c;
        } else {
            Nodo k = ptr;
            while (k != null) {
                if (k.getProd().substring(0, 1).equals(nt)) {
                    k.setProd(k.getProd() + "|" + p.split(">")[1]);
                    break;
                } else {
                    if (k.link == null) {
                        Nodo n = new Nodo(p);
                        k.link = n;
                        break;
                    }
                    k = k.link;
                }
            }
        }
    }
    
    public void agregar_prod2(String p) {
        String nt = p.substring(0, 1);
        if (ptr == null) {
            Nodo c = new Nodo(p);
            ptr = c;
        } else {
            Nodo k = ptr;
            while (k.link != null) {
                k = k.link;
            }
            Nodo n = new Nodo(p);
            k.link = n;
        }
    }

    public void rapartir() {
        Nodo k = ptr;
        while(k != null){
            for(int i = 0; i < k.getProd().length(); i++){
                if(Character.isUpperCase(k.getProd().charAt(i))){
                    dame_prima(k.getProd().charAt(i));
                }
            }
            k = k.link;
        }
    }

    public void mostrar_prod() {
        Nodo p = ptr;
        String prueba;
        while (p != null) {
            if (!"-1".equals(tienerecursividad(p.getProd()))) {
                elim_rec2(p);

            }
            if (!probadas.contains(p.getProd().charAt(0))) {
                hay_fact(p.getProd());
            }
            System.out.println(p.getProd());
            p = p.link;
        }
    }

    int tamaño() {
        int i = 0;
        Nodo p = ptr;
        while (p != null) {
            i++;
            p = p.link;
        }
        return i;
    }

    public void elim_rec(String p) {
        String[] prods = p.split("\\|");
        String alfa = "", prima, nueva;
        String beta = "";
        Nodo k = ptr;
        int i = 0, cont = 0, j = 0, posi, h = 0, t, cont2 = 0;
        String pos;
        while (k != null) {
            if (k.getProd().equals(p)) {
                pos = tienerecursividad(k.getProd());
                if (!"-1".equals(pos)) {
                    String[] r = pos.split("_");
                    while (j < r.length) {
                        posi = Integer.parseInt(r[j]);
                        if (j == 0) {
                            if (posi == 0) {
                                alfa = prods[posi].substring(4, prods[posi].length()) + p.substring(0, 1) + "'";
                            } else {
                                alfa = prods[posi].substring(1, prods[posi].length()) + p.substring(0, 1) + "'";
                            }
                        } else {
                            if (posi == 0) {
                                alfa = alfa + "|" + prods[posi].substring(4, prods[posi].length()) + p.substring(0, 1) + "'";
                            } else {
                                alfa = alfa + "|" + prods[posi].substring(1, prods[posi].length()) + p.substring(0, 1) + "'";
                            }
                        }
                        j++;
                    }
                    while (i < prods.length) {
                        cont2 = 0;
                        h = 0;
                        while (h < r.length) {
                            t = Integer.parseInt(r[h]);
                            if (i == t) {
                                cont2++;
                            }
                            h++;
                        }
                        if (cont2 == 0) {
                            if (i == 0) {
                                beta = prods[i].substring(3, prods[i].length()) + p.substring(0, 1) + "'";
                                cont++;
                            } else {
                                if (cont == 0) {
                                    beta = prods[i] + p.substring(0, 1) + "'";
                                    cont++;
                                } else {
                                    beta = beta + "|" + prods[i] + p.substring(0, 1) + "'";
                                }
                            }
                            cont++;
                        }
                        i++;
                    }
                }
                if (beta.equals("")) {
                    beta = p.substring(0, 1) + "'";
                }
                nueva = p.substring(0, 1) + "->" + beta;
                prima = p.substring(0, 1) + "'" + "->" + alfa + "|&";
                k.setProd(nueva);
                Nodo temp = k.link;
                Nodo n = new Nodo(prima);
                k.link = n;
                n.link = temp;
                break;
            } else {
                k = k.link;
            }
        }
    }

    public void elim_rec2(Nodo p) {
        String prod = p.getProd();
        String alfa = p.getProd().substring(4, p.getProd().length());
        String prima = dame_prima(p.getProd().charAt(0));
        agregar_prima(p.getProd(), prima);
        if(ya_e(prima)){
            agregar_prod2(prima + "->&");
        }
        primas[indice][0] = p.getProd().substring(0, 1);
        p.setProd(prima + "->" + alfa + prima);
        primas[indice][1] = prima;
        indice++;
    }

    boolean ya_e(String p) {
        Nodo k = ptr;
        while(k != null){
            if(k.getProd().equals(p.charAt(0)+"->&")){
                return false;
            }
            k = k.link;
        }
        return true;
    }

    public void agregar_prima(String p, String prima) {
        Nodo k = ptr;
        while (k != null) {
            if (k.getProd().substring(0, 1).equals(p.substring(0, 1)) && k.tp == false && "-1".equals(tienerecursividad(k.getProd()))) {
                k.setProd(k.getProd() + prima);
                k.tp = true;
            }
            k = k.link;
        }
    }

    String dame_prima(char p) {
        String[] abecedario = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
        Nodo k = ptr;
        int j = 0, t = primas.length, y = 0;
        String prima, prueba1, prueba2;
        while (j < indice2) {
            if (Character.toString(p).equals(primas[j][0])) {
                return primas[j][1];
            } else {
                j++;
            }
        }
        String pureba;
        while (k != null){
            y = indice3;
            for (int i = 0; i < k.getProd().length(); i++) {
                pureba = Character.toString(k.getProd().charAt(i));
                prueba2 = abecedario[indice3];
                if (Character.toString(k.getProd().charAt(i)).equals(abecedario[indice3])) {
                    indice3++;
                    break;
                }
            }
            if(y == indice3 -1){
                k = ptr;
            }else{
                k = k.link;
            }
        }
        primas[indice2][0] = Character.toString(p);
        primas[indice2][1] = abecedario[indice3];
        indice2++;
        indice3++;
        return abecedario[indice2 - 1];
    }

    boolean hay_fact(String p) {
        String prima;
        int i, cont = 0, cont2 = 0, j = 0;
        probadas.add(p.charAt(0));
        ArrayList<String> fact = new ArrayList<>();
        ArrayList<String> list = a_comparar(p);
        ArrayList<String> ro;
        ArrayList<String> beta;
        ArrayList<ArrayList<String>> r = new ArrayList();
        String prueba, alfa = null, mayor = "0", tamaño = "0";
        for (String k : list) {
            i = k.length();
            while (i > 3) {
                prueba = k.substring(3, i);
                cont = -1;
                for (String l : list) {
                    if ((l.length() - 3) >= prueba.length()) {
                        if (prueba.equals(l.substring(3, 3 + prueba.length()))) {
                            cont++;
                        }
                    }
                }
                fact.add(k + "cris" + prueba + "cris" + cont + "cris" + prueba.length());
                i--;
            }
        }

        for (String f : fact) {
            String[] factores = f.split("cris");
            if (!factores[2].equals("0")) {
                cont2++;
            }
            if (factores[2].compareTo(mayor) > 0) {
                if (factores[2].compareTo(mayor) == 0) {
                    if (factores[3].compareTo(tamaño) > 0) {
                        mayor = factores[2];
                        alfa = factores[1];
                        tamaño = factores[3];
                    }
                } else {
                    mayor = factores[2];
                    alfa = factores[1];
                    tamaño = factores[3];
                }
            }
        }
        if (cont2 == 0) {
            return false;
        } else {
            r = ro(list, alfa);
            ro = r.get(0);
            beta = r.get(1);
            quitar_fact(p, ro, beta, alfa);
            return true;
        }
    }

    ArrayList a_comparar(String prod) {
        ArrayList<String> r = new ArrayList<>();
        Nodo k = ptr;
        while (k != null) {
            if (k.getProd().charAt(0) == prod.charAt(0)) {
                r.add(k.getProd());
            }
            k = k.link;
        }
        return r;
    }

    public void quitar_fact(String prod, ArrayList<String> ro, ArrayList<String> beta, String alfa) {
        Nodo k = ptr;
        Nodo i = null, ant = null;
        int primero = 0;
        String prima;
        while (k != null) {
            if (k.getProd().charAt(0) == prod.charAt(0)) {
                if (primero == 0) {
                    i = k;
                    primero++;
                    ant = k;
                    k = k.link;
                } else {
                    ant.link = k.link;
                    k = null;
                    k = ant.link;
                }
            } else {
                k = k.link;
            }
        }
        prima = dame_prima(prod.charAt(0));
        i.setProd(prod.charAt(0) + "->" + alfa + prima);
        Nodo temp = i.link;
        for (String ri : ro) {
            Nodo t1 = new Nodo(ri);
            i.link = t1;
            i = i.link;
        }
        for (String bi : beta) {
            Nodo t1 = new Nodo(prima + "->" + bi);
            i.link = t1;
            i = i.link;
        }
        i.link = temp;
    }

    ArrayList<ArrayList<String>> ro(ArrayList<String> list, String alfa) {
        ArrayList<String> ro = new ArrayList();
        ArrayList<String> beta = new ArrayList();
        ArrayList<ArrayList<String>> r = new ArrayList();
        int lengt;
        for (String l : list) {
            lengt = l.length();
            if (lengt >= 3 + alfa.length()) {
                if (!l.substring(3, 3 + alfa.length()).equals(alfa)) {
                    ro.add(l);
                } else {
                    if (l.substring(3 + alfa.length(), l.length()).equals("")) {
                        beta.add("&");
                    } else {
                        beta.add(l.substring(3 + alfa.length(), l.length()));
                    }
                }
            } else {
                ro.add(l);
            }
        }
        r.add(ro);
        r.add(beta);

        return r;
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        int isselected = chooser.showSaveDialog(null);
        String line;
        file = chooser.getSelectedFile();
        if (isselected == JFileChooser.APPROVE_OPTION) {
            file_path.setText(file.getAbsolutePath());
            BufferedReader reader;
            try {
                reader = new BufferedReader(new FileReader(file));
                line = reader.readLine();
                while (line != null) {
                    agregar_prod2(line);
                    line = reader.readLine();
                }
                rapartir();
                mostrar_prod();
            } catch (Exception e) {
                System.out.println("eeeeeeeeeeeeeeeeeeeeeeeeeeeeee");
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField file_path;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
